Домашнее задание №2
Frontend-Sirius-VK/2022-autumn-d.usov pull request #2
Opened 2022-12-02 09:14 UTC by DanielUsov

2022-12-08 20:49 UTC, Betchika99 requested changes
- [x] не открывается главная страница: Refused to apply style from 'http://localhost:3000/FrontEnd/style.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.
- [ ] верстка страницы неполная - нет чекбоксов для отмеченных/неотмеченных событий, не отображается описание, дизайн практически отсутствует (что не соответствует заявленному оригиналу)
- [ ] не очень понятно, зачем нужна директория /src/Server/controller
- [ ] index.html - это не серверный файл, надо перенести его в директорию фронтенда
- [ ] fyi чаще всего папки и файлы на фронтенде называют с маленькой буквы :)

архитектурно всё корректно, молодец. большой вопрос к верстке (продуктовые требования пока не выполнены). **дедлайн на исправления: 11.12 10:00**

2022-12-08 20:49 UTC, Betchika99 commented on package.json
> +	"license": "ISC"
ой ой, тут табы лучше не менять

2022-12-08 20:49 UTC, Betchika99 commented on src/FrontEnd/components/TasksCard/TasksCard.js
> +		// tasksCard.append(tasksHeader, tasksDescription);
комменты и логи убираем перед сдачей ДЗ на проверку

2022-12-08 20:49 UTC, Betchika99 commented on src/FrontEnd/components/TasksCardRender/TasksCardRender.js
> +		data.forEach((task) => {
а если в data пришел не массив, а что-то другое? тут упадет код и будет белый экран (можно проверить, если отключить базу данных)

2022-12-08 20:49 UTC, Betchika99 commented on src/FrontEnd/model/TaskData.js
> +				// console.log(data);
логи убираем

2022-12-08 20:49 UTC, Betchika99 commented on src/FrontEnd/view/MainView.js
> +		root.append(this.container);
если на строке 12 root не был найден, то здесь будет исключение. надо проверить, что в этой переменной действительно что-то есть, прежде чем аппендить

2022-12-08 20:49 UTC, Betchika99 commented on src/FrontEnd/view/MainView.js
> +	update(data = {}) {
дата - это массив. поэтому в качестве данных по умолчанию должен быть [], а не {}

2022-12-08 20:49 UTC, Betchika99 commented on src/Server/Server.js
> +app.get('/', async (req, res) => {
зачем здесь async?

2022-12-08 20:49 UTC, Betchika99 commented on src/Server/Server.js
> +app.get('/getTasks', async (req, res) => {
давай придерживаться REST-а, мы же именно его с вами проходили :)

2022-12-08 20:49 UTC, Betchika99 commented on src/Server/Server.js
> +	const result = await task.getAllTasks();
await обычно оборачивают в try catch

2022-12-10 15:26 UTC, DanielUsov commented on package.json
> +	"license": "ISC"
Это происходит из-за проблем отображения файла в git, локально все нормально

2022-12-11 21:41 UTC, Betchika99 approved these changes, later dismissed
- [x] is_done не проставляется 
- [ ] по нажатию на текст рядом с чекбоксом не проставляется галочка, нужно пофиксить (и добавить cursor: pointer)
- [x] давай урлы и названия событий будем делать с маленькой буквы (так принято)

2022-12-11 21:41 UTC, Betchika99 commented on src/FrontEnd/components/tasksList/tasksList.css
> +	/* background-color: initial; */
комменты убираем перед сдачей ДЗ на проверку

2022-12-12 20:50 UTC, Betchika99 approved these changes

2022-12-12 20:51 UTC, merged